export const REDIS_PREFIXES = {
    METER_CACHE: 'meter:',
    ORDER_DEDUPE: 'order:',
    METER_VALIDATION: 'validate:',
    PAYMENT_CACHE: 'payment:',
    WEBHOOK: 'wh:',
    WEBHOOK_EVENT: 'wh:event:',
    RATE_LIMIT: 'rate:',
    IP_WHITELIST: 'ip:whitelist:',
    PAYMENT_STATUS: 'payment_status:',
    VENDING_RETRY: 'vending_retry:',
    BANK_LIST_CACHE_KEY: 'monnify:bankList',
    MANDATE: 'mandate:',
    DIRECT_DEBIT_ACCOUNT_LOCK: 'dd_account_lock:',
    DIRECT_DEBIT_MANDATE_CACHE: 'dd_mandate:',
    DISCO_HEALTH: 'disco_health:',
};