name: Deploy to Azure

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        uses: azure/webapps-deploy@v2
        with:
          app-name: energiease-staging
          slot-name: staging
          package: .

    #   - name: Deploy to Production
    #     if: github.ref == 'refs/heads/main'
    #     uses: azure/webapps-deploy@v2
    #     with:
    #       app-name: energiease-prod
    #       package: .
